// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "910c57f9-0e2a-465f-9494-d7f45198c917");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1570617112);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1570616632);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1570616872);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1570616752);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1570616992);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1570616604);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{925a822c-b7f4-471b-84e8-b7bdaa9d5480}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1570559400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1570616675827");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1570618453827");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1570616616599");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1570620216599");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1570616612");
user_pref("browser.slowStartup.averageTime", 32249);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190128144255");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1570616614143");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "0b7773bbed1a48ada2521e7328b02bd8");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1570617114);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"71498551-d279-45f8-83a0-af85cbd626ff\",\"screenshots@mozilla.org\":\"16e8b365-1cf3-4074-ba5d-b9ebb7a2a240\",\"webcompat-reporter@mozilla.org\":\"63534ad0-95fe-45b0-87da-37a45dd564cc\",\"webcompat@mozilla.org\":\"28527e2c-6bcf-4abd-bc17-0028600a6050\",\"baidu-code-update@mozillaonline.com\":\"6ba86e2e-7341-4a1c-b290-ee86bc84766d\",\"fxmonitor@mozilla.org\":\"df21efed-dbf5-40b1-8b56-b36961ee4e12\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1570616738);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190128144255");
user_pref("media.gmp-manager.lastCheck", 1570616735);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "0abcf672-3c85-46c1-9066-3767e522cb1b");
user_pref("security.sandbox.plugin.tempDirSuffix", "8d764db7-683d-43a1-a531-33f1f232c23e");
user_pref("services.blocklist.addons.checked", 1570616764);
user_pref("services.blocklist.gfx.checked", 1570616764);
user_pref("services.blocklist.onecrl.checked", 1570616764);
user_pref("services.blocklist.pinning.checked", 1570616764);
user_pref("services.blocklist.plugins.checked", 1570616764);
user_pref("services.settings.clock_skew_seconds", -274);
user_pref("services.settings.last_etag", "\"1570579719049\"");
user_pref("services.settings.last_update_seconds", 1570617266);
user_pref("services.settings.main.language-dictionaries.last_check", 1570616764);
user_pref("services.settings.main.sites-classification.last_check", 1570616764);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1570616583);
user_pref("toolkit.telemetry.cachedClientID", "775504f9-6d74-41b3-a8de-ac6cba353f19");
user_pref("toolkit.telemetry.previousBuildID", "20190128144255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
